SELECT SESSION_NAME from AD_ACADEMIC_SESSION;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY*12 from EMPLOYEES;

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID=90;

SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE LAST_NAME='King';

SELECT DISTINCT LAST_NAME FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE HIRE_DATE='07-JUNE-10';

SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 3500 AND 6000;

SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN (100,200,102);

SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '%n%';

SELECT * FROM EMPLOYEES WHERE JOB_ID LIKE '___%';

SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;

SELECT * FROM EMPLOYEES WHERE SALARY >= 5000 AND JOB_ID LIKE '%MAN%';

SELECT * FROM EMPLOYEES WHERE SALARY >= 10000 OR JOB_ID LIKE '%MAN%';